DAT 3587
Datical/liquibase pull request #162
Opened 2019-11-27 17:16 UTC by wwillard7800

…option

2019-12-04 16:53 UTC, nvoxland requested changes

2019-12-04 16:53 UTC, nvoxland commented on liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
> +            System.out.println("HERE!!!!!!!!!!!!!!!!!!!");
Need to remove this

2019-12-04 16:57 UTC, wwillard7800 commented
Oops.

On Wed, Dec 4, 2019 at 10:53 AM Nathan Voxland <notifications@github.com>
wrote:

> *@nvoxland* requested changes on this pull request.
> ------------------------------
>
> In
> liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
> <https://github.com/Datical/liquibase/pull/162#discussion_r353862286>:
>
> > @@ -1133,6 +1140,7 @@ public URLClassLoader run() {
>       */
>      protected void doMigration() throws Exception {
>          if (COMMANDS.HELP.equalsIgnoreCase(command)) {
> +            System.out.println("HERE!!!!!!!!!!!!!!!!!!!");
>
> Need to remove this
>
> —
> You are receiving this because you authored the thread.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Datical/liquibase/pull/162?email_source=notifications&email_token=AAHAEDGXGMGUUVVOB6TK56TQW7N7LA5CNFSM4JSJ6R72YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCN6Z7DY#pullrequestreview-326999951>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHAEDETIRZBEUXHRKJ2HZ3QW7N7LANCNFSM4JSJ6R7Q>
> .
>

2019-12-04 17:01 UTC, neupsh commented on liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
> +            System.out.println("HERE!!!!!!!!!!!!!!!!!!!");
Hahaha :) :+1: nice find :P

2019-12-05 16:54 UTC, nvoxland approved these changes

2019-12-18 21:34 UTC, merged